// <auto-generated />
namespace HC.CommonObjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Doctor_Table_IsInternalCreated_ColumnAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Doctor_Table_IsInternalCreated_ColumnAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201810261049474_Doctor_Table_IsInternalCreated_ColumnAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
