// <auto-generated />
namespace HC.CommonObjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Doctor_Table_Added1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Doctor_Table_Added1));
        
        string IMigrationMetadata.Id
        {
            get { return "201810260806248_Doctor_Table_Added1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
