// <auto-generated />
namespace HC.CommonObjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class User_Table_IsInternalUser_Modify : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Table_IsInternalUser_Modify));
        
        string IMigrationMetadata.Id
        {
            get { return "201810261100171_User_Table_IsInternalUser_Modify"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
