// <auto-generated />
namespace HC.CommonObjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Specialization_AllowNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Specialization_AllowNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201810241227027_Specialization_AllowNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
